import { Injectable } from "@nestjs/common";
import { PrismaService } from "../prisma/prisma.service";

@Injectable()
export class AiService {
  constructor(private readonly prisma: PrismaService) {}

  async summarizeDailyWork(userId: string, dateStr?: string) {
    const targetDate = dateStr ? new Date(dateStr) : new Date();
    targetDate.setHours(0, 0, 0, 0);

    const update = await this.prisma.client.dailyUpdate.findUnique({
      where: { userId_date: { userId, date: targetDate } },
    });

    if (!update) {
      return "No daily update found for this user on the selected date.";
    }

    const completed = update.completedItems.map((item) => `- ${item}`).join("\n");
    const planned = update.plannedItems.map((item) => `- ${item}`).join("\n");

    return `### Work Summary for ${targetDate.toISOString().split("T")[0]}\n\n**Completed Today:**\n${completed}\n\n**Planned for Tomorrow:**\n${planned}\n\n*Summary generated by OfficeOS AI.*`;
  }

  async answerPolicyQuestion(companyId: string, question: string) {
    // Basic keyword RAG simulation over Knowledge Base SOPs/articles
    const keywords = question.toLowerCase().split(" ").filter((k) => k.length > 3);
    
    const articles = await this.prisma.client.knowledgeBaseArticle.findMany({
      where: { companyId },
      take: 5,
    });

    // Find best matching article based on keyword overlap
    let bestArticle: any = null;
    let maxOverlap = 0;

    for (const art of articles) {
      const titleLower = art.title.toLowerCase();
      const contentLower = art.content.toLowerCase();
      let overlap = 0;

      for (const kw of keywords) {
        if (titleLower.includes(kw)) overlap += 3;
        if (contentLower.includes(kw)) overlap += 1;
      }

      if (overlap > maxOverlap) {
        maxOverlap = overlap;
        bestArticle = art;
      }
    }

    if (bestArticle && maxOverlap > 0) {
      return `Based on the company document **"${bestArticle.title}"**:\n\n${bestArticle.content.slice(0, 500)}...\n\n*Reference: Knowledge Base article [Link].*`;
    }

    return "I couldn't find a specific policy document addressing that question. Please try asking HR or search the Knowledge Base directly.";
  }

  async analyzeProjectRisks(projectId: string) {
    const project = await this.prisma.client.project.findUnique({
      where: { id: projectId },
      include: { risks: true },
    });

    if (!project) return "Project not found.";
    if (project.risks.length === 0) return "No active risks logged for this project. Keep up the good monitoring!";

    const risksSummary = project.risks
      .map((r) => `- **${r.title}** (${r.severity} severity): Mitigation: ${r.mitigation ?? "None logged"}`)
      .join("\n");

    return `### AI Project Risk Analysis for **${project.name}**\n\n**Active Risks:**\n${risksSummary}\n\n**Recommendation:**\nEnsure regular sprint check-ins focus on mitigating High/Critical items. Assign risk owners.`;
  }
}
